server:
  port: 8084
  servlet:
    context-path: /api_user
spring:
  application:
    name: user
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/db_api_user
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost